language: node_js
node_js:
  - "4.1"
before_scrpt: 
  - npm install gulp
script: gulp
bundler_args: --retry 3
install: travis_retry bundle install
install: travis_wait mvn install
cache:
  directories:
    - node_modules